const base="https://www.dvd-dental.com";
const url=base+"/composite-filtek-supreme-xte-jeringas-3g/";
const headers={"user-agent":"DentalPrice/0.1 (+https://github.com/avancedental74/dental-price; single-user price research)",accept:"text/html,application/xhtml+xml"};
const response=await fetch(url,{headers});
const html=await response.text();
const flat=html.replace(/\s+/g," ");
const productId=html.match(/name=["']product_id["'][^>]*value=["'](\d+)["']/i)?.[1] ?? html.match(/product_id:\s*["']?(\d+)/i)?.[1] ?? "795";
const attr=html.match(/name=["']attribute\[(\d+)\]["'][^>]*value=["']1529["']/i)?.[1] ?? "491";
const body=new URLSearchParams({action:"add",product_id:productId,"qty[]":"1",[`attribute[${attr}]`]:"1529"});
const vr=await fetch(base+`/remote/v1/product-attributes/${productId}`,{method:"POST",headers:{"user-agent":headers["user-agent"],accept:"application/json","content-type":"application/x-www-form-urlencoded"},body:body.toString()});
const text=await vr.text();
console.log(JSON.stringify({pageStatus:response.status,productId,attributeId:attr,variantStatus:vr.status,variantContentType:vr.headers.get("content-type"),variantBody:text.slice(0,6000)},null,2));